version: '3.7'

services:
  app:
    runtime: nvidia
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - CUDA_VISIBLE_DEVICES=0
      - NVIDIA_DRIVER_CAPABILITIES=all
      - DIR_PATH=/app
      - WANDB_API_KEY=8e7723e403e3ae56bfc42782e890c8ac109c2de5
